### ISSUE TITLE
Additional documentation request to clarify connecting to solr

### ISSUE THREAD

**Issue by gswartz777** [solr-express/solr-express#238]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
</code></pre>

## Other

I'm trying to get solr-express set up but the documentation doesn't provide enough information for me to fully understand.  I have a .net solution containing 2 projects.  One is my mvc app with ninject installed.  The other is my domain project with my models, data, etc.  I have set up my NinjectWebCommon file in the mvc app with the following...

<pre><code>
private static void RegisterServices(IKernel kernel)
{
     kernel.AddSolrExpress<AgencyDocument>(builder => builder.UseHostAddress(SolrConstants.LiveServer).UseSolr5());           
}
</code></pre>

However I'd really want my querying and such to be done in my data layer and have my mvc app call that.  So I'm not quite sure how to do that.  In your examples you have DocumentCollection<TechProductDocument> documentCollection; // from DI and passing it into a method.  Can you explain this a bit more from an application such as mine?  How does my domain layer connect to solr?

**Comment by diegobrum** [comment]
Hi @gswartz777 

I had created SolrExpress using SOLID principles in mind (and I really hope I have achieved this :D )
Because this, I use a lot of interfaces to provide specific implementations in Solr 4.x and Solr 5.x (and in future Solr 6.x and 7.x)
When you do this...
``` csharp
<DI container>
    .AddSolrExpress<TechProduct1>(builder => builder
        .UseHostAddress("<some address>")
        .UseSolr5());
```
...you configure a lot of implementations (including DocumentCollection<TechProduct1>).

So, you can use DocumentCollection<TechProduct1> in constructor of some class (because DI mechanism, in your case Ninject).

If you use SolrExpress in your Data project and configure DI in MCV app, this will work correct (if this is a good practice or not, is another question).

Did I answer your question correctly?
